# PLENUM — start the API and the web dev server together (R11).
# Prereqs: docker compose up -d  (database)  and  cargo run --bin seed  (data).
# Each server opens in its own window so its logs stay visible and Ctrl-C in
# one never kills the other.
#
# Fresh-clone friendliness (gate P5-1): .env is gitignored, and without one
# the API defaults COOKIE_SECURE=true (production posture) — which makes a
# plain-HTTP localhost browser refuse to send the session cookie back. So if
# no .env exists, this script materializes the DEV one first. The values it
# writes are the dev-only credentials already committed in docker-compose.yml
# and docker/initdb/01-app-role.sql — localhost demo values, not secrets; the
# AI keys stay empty (AI off) until you add your own.

$repo = Split-Path -Parent $PSScriptRoot

if (-not (Test-Path (Join-Path $repo ".env"))) {
    @(
        "# Generated by scripts/run-all.ps1 — dev-only values matching docker-compose.yml.",
        "DATABASE_URL=postgres://plenum_admin:plenum_dev_admin_pw@localhost:5434/plenum",
        "APP_DATABASE_URL=postgres://plenum_app:plenum_dev_app_pw@localhost:5434/plenum",
        "COOKIE_SECURE=false",
        "BIND_ADDR=127.0.0.1:5777",
        "RUST_LOG=info",
        "ANTHROPIC_API_KEY=",
        "ANTHROPIC_MODEL=claude-sonnet-5",
        "AI_ASK_ENABLED=true",
        "AI_DISCOUNT_ENABLED=true"
    ) | Set-Content -Encoding UTF8 (Join-Path $repo ".env")
    Write-Host "wrote a dev .env (no key material — add ANTHROPIC_API_KEY yourself for live AI)"
}

if (-not (Test-Path (Join-Path $repo "web\node_modules"))) {
    Write-Host "web/node_modules missing — running npm install once..."
    Push-Location (Join-Path $repo "web")
    npm install
    Pop-Location
}

Start-Process cmd -ArgumentList "/k", "title PLENUM API && cargo run --bin api" -WorkingDirectory $repo
Start-Process cmd -ArgumentList "/k", "title PLENUM web && npm run dev" -WorkingDirectory (Join-Path $repo "web")

Write-Host ""
Write-Host "PLENUM starting in two windows:"
Write-Host "  API -> http://127.0.0.1:5777   (window: PLENUM API)"
Write-Host "  web -> http://127.0.0.1:5177   (window: PLENUM web)"
Write-Host ""
Write-Host "Open http://127.0.0.1:5177 and log in from the seed's login table"
Write-Host "(password for every demo user: demo-plenum-2026)."
